/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phs.Gui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import phs.Classes.DBConnector;
import phs.Classes.Database;

/**
 *
 * @author Boznea, Stefan Dimitriu, Alexandru Lazaroiu, Bogdan Nedelea
 */
public class scheme extends javax.swing.JFrame {

    /**
     * Creates new form scheme
     */
    public scheme() {
        initComponents();
    }

    public static void update2(int id, String verde) throws SQLException {
        try {//set (subject, priority, status, comment)
            Connection conn = DBConnector.getConnection();
            String query = "UPDATE color SET colour = ? WHERE id = ?";

            System.out.println(query);
            try (PreparedStatement pstmt = conn.prepareStatement(query)) {
                pstmt.setString(1, verde);
                pstmt.setInt(2, id);
                pstmt.executeUpdate();
            }

        } catch (SQLException ex) {
            Logger.getLogger(Database.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static void update(int room, String customer_name, String checkin, String checkout, Double total_sum) throws SQLException {
        try {//set (subject, priority, status, comment)
            Connection conn = DBConnector.getConnection();
            String query = "UPDATE rooms SET customer_name = ?, checkin = ?, checkout = ?, total_sum = ? WHERE room = ?";

            System.out.println(query);
            try (PreparedStatement pstmt = conn.prepareStatement(query)) {
                pstmt.setString(1, customer_name);
                pstmt.setString(2, checkin);
                pstmt.setString(3, checkout);
                pstmt.setDouble(4, total_sum);
                pstmt.setInt(5, room);
                pstmt.executeUpdate();
            }

        } catch (SQLException ex) {
            Logger.getLogger(scheme.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("------------End-----------");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        label1 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        label1.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
        label1.setForeground(new java.awt.Color(51, 102, 255));
        label1.setText("Plaza Hotel");

        jLabel1.setText("Room :");

        jLabel2.setText("Name :");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Check-In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 204, 102));
        jButton2.setText("Check-out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Date In :");

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Date Out :");

        jLabel5.setText("Payment :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                                .addGap(100, 100, 100))
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        try {
            if (systemgui.ok == 1) {
                systemgui.jButton1.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 2) {
                systemgui.jButton2.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 3) {
                systemgui.jButton3.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 4) {
                systemgui.jButton4.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 5) {
                systemgui.jButton5.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 6) {
                systemgui.jButton6.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 7) {
                systemgui.jButton7.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 8) {
                systemgui.jButton8.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 9) {
                systemgui.jButton9.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 10) {
                systemgui.jButton10.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 11) {
                systemgui.jButton11.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 12) {
                systemgui.jButton12.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 13) {
                systemgui.jButton13.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 14) {
                systemgui.jButton14.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 15) {
                systemgui.jButton15.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 16) {
                systemgui.jButton16.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 17) {
                systemgui.jButton17.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 18) {
                systemgui.jButton18.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 19) {
                systemgui.jButton19.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 20) {
                systemgui.jButton20.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 21) {
                systemgui.jButton21.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 22) {
                systemgui.jButton22.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 23) {
                systemgui.jButton23.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 24) {
                systemgui.jButton24.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 25) {
                systemgui.jButton25.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 26) {
                systemgui.jButton26.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 27) {
                systemgui.jButton27.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 28) {
                systemgui.jButton28.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 29) {
                systemgui.jButton29.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 30) {
                systemgui.jButton30.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 31) {
                systemgui.jButton31.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 32) {
                systemgui.jButton32.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 33) {
                systemgui.jButton33.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 34) {
                systemgui.jButton34.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 35) {
                systemgui.jButton35.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 36) {
                systemgui.jButton36.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 37) {
                systemgui.jButton37.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 38) {
                systemgui.jButton38.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 39) {
                systemgui.jButton39.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 40) {
                systemgui.jButton40.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 41) {
                systemgui.jButton41.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 42) {
                systemgui.jButton42.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 43) {
                systemgui.jButton43.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 44) {
                systemgui.jButton44.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 45) {
                systemgui.jButton45.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 46) {
                systemgui.jButton46.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 47) {
                systemgui.jButton47.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 48) {
                systemgui.jButton48.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 49) {
                systemgui.jButton49.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            } else if (systemgui.ok == 50) {
                systemgui.jButton50.setBackground(new java.awt.Color(255, 0, 0));
                update2(systemgui.ok, "red");
            }
        } catch (SQLException ex) {
            Logger.getLogger(scheme.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Connection conn = DBConnector.getConnection();
            String sql = "SELECT * FROM rooms";

            System.out.println(sql);
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.executeQuery();
            ResultSet rs = pstmt.getResultSet();
            String temp1 = jTextField1.getText();
            int room = Integer.parseInt(temp1);
            String customer_name = jTextField2.getText();
            String checkin = jTextField3.getText();
            String checkout = jTextField4.getText();
            String temp_sum = jTextField5.getText();
            Double total_sum = Double.parseDouble(temp_sum);
            update(room, customer_name, checkin, checkout, total_sum);

        } catch (SQLException ex) {
            Logger.getLogger(scheme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    ///
    public String calculations(int room, String First, String Second) {
        int price = 0;
        if (room < 21) {
            price = 66;
        } else if (room > 20 && room < 41) {
            price = 84;
        } else if (room > 40 && room < 51) {
            price = 100;
        }
        String out = Second;
        String in = First;
        char a = (char) (in.charAt(0) * 10 + in.charAt(1));
        System.out.println(a);
        System.out.println();
        char b = (char) (out.charAt(0) * 10 + out.charAt(1));
        System.out.println(b);
        System.out.println();
        char c = (char) (b - a);
        System.out.println(c);
        System.out.println();
        double d = (-1)*price * (double) (c - '0');
        String e = d+"";
        System.out.println(e);
        return e;

    }

    ///
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        try {
            if (systemgui.ok == 1) {
                systemgui.jButton1.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 2) {
                systemgui.jButton2.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 3) {
                systemgui.jButton3.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 4) {
                systemgui.jButton4.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 5) {
                systemgui.jButton5.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 6) {
                systemgui.jButton6.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 7) {
                systemgui.jButton7.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 8) {
                systemgui.jButton8.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 9) {
                systemgui.jButton9.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 10) {
                systemgui.jButton10.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 11) {
                systemgui.jButton11.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 12) {
                systemgui.jButton12.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 13) {
                systemgui.jButton13.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 14) {
                systemgui.jButton14.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 15) {
                systemgui.jButton15.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 16) {
                systemgui.jButton16.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 17) {
                systemgui.jButton17.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 18) {
                systemgui.jButton18.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 19) {
                systemgui.jButton19.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 20) {
                systemgui.jButton20.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 21) {
                systemgui.jButton21.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 22) {
                systemgui.jButton22.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 23) {
                systemgui.jButton23.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 24) {
                systemgui.jButton24.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 25) {
                systemgui.jButton25.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 26) {
                systemgui.jButton26.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 27) {
                systemgui.jButton27.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 28) {
                systemgui.jButton28.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 29) {
                systemgui.jButton29.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 30) {
                systemgui.jButton30.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 31) {
                systemgui.jButton31.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 32) {
                systemgui.jButton32.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 33) {
                systemgui.jButton33.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 34) {
                systemgui.jButton34.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 35) {
                systemgui.jButton35.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 36) {
                systemgui.jButton36.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 37) {
                systemgui.jButton37.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 38) {
                systemgui.jButton38.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 39) {
                systemgui.jButton39.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 40) {
                systemgui.jButton40.setBackground(new java.awt.Color(0, 204, 102));
                update2(systemgui.ok, "green");
            } else if (systemgui.ok == 41) {
                systemgui.jButton41.setBackground(new java.awt.Color(255, 255, 0));
                update2(systemgui.ok, "yellow");
            } else if (systemgui.ok == 42) {
                systemgui.jButton42.setBackground(new java.awt.Color(255, 255, 0));
                update2(systemgui.ok, "yellow");
            } else if (systemgui.ok == 43) {
                systemgui.jButton43.setBackground(new java.awt.Color(255, 255, 0));
                update2(systemgui.ok, "yellow");
            } else if (systemgui.ok == 44) {
                systemgui.jButton44.setBackground(new java.awt.Color(255, 255, 0));
                update2(systemgui.ok, "yellow");
            } else if (systemgui.ok == 45) {
                systemgui.jButton45.setBackground(new java.awt.Color(255, 255, 0));
                update2(systemgui.ok, "yellow");
            } else if (systemgui.ok == 46) {
                systemgui.jButton46.setBackground(new java.awt.Color(255, 255, 0));
                update2(systemgui.ok, "yellow");
            } else if (systemgui.ok == 47) {
                systemgui.jButton47.setBackground(new java.awt.Color(255, 255, 0));
                update2(systemgui.ok, "yellow");
            } else if (systemgui.ok == 48) {
                systemgui.jButton48.setBackground(new java.awt.Color(255, 255, 0));
                update2(systemgui.ok, "yellow");
            } else if (systemgui.ok == 49) {
                systemgui.jButton49.setBackground(new java.awt.Color(255, 255, 0));
                update2(systemgui.ok, "yellow");
            } else if (systemgui.ok == 50) {
                systemgui.jButton50.setBackground(new java.awt.Color(255, 255, 0));
                update2(systemgui.ok, "yellow");
            }
        } catch (SQLException ex) {
            Logger.getLogger(scheme.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            Connection conn = DBConnector.getConnection();
            String sql = "SELECT * FROM rooms";

            System.out.println(sql);
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.executeQuery();
            ResultSet rs = pstmt.getResultSet();
            String temp1 = jTextField1.getText();
            int room = Integer.parseInt(temp1);
            update(room, "", "", "", 0.0);

        } catch (SQLException ex) {
            Logger.getLogger(scheme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    public String Time() {
        Calendar cal = Calendar.getInstance();
        cal.getTime();
        SimpleDateFormat ITime = new SimpleDateFormat("dd/MM/yyyy");
        String LTime = ITime.format(cal.getTime());
        return LTime;
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            Connection conn = DBConnector.getConnection();
            String x = systemgui.ok + "";
            String sql = "SELECT * FROM rooms WHERE room =" + x;

            System.out.println(sql);
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.executeQuery();

            ResultSet rs = pstmt.getResultSet();
            if (rs.next()) {
                int room = rs.getInt("room");
                String customer_name = rs.getString("customer_name");
                String checkin = rs.getString("checkin");
                String checkout = rs.getString("checkout");
                Double total_sum = rs.getDouble("total_sum");
                System.out.println(" " + room + " " + customer_name + " " + checkin + " " + checkout + " " + total_sum);
                String s = room + "";
                jTextField1.setText(s);
                jTextField2.setText(customer_name);
                if (checkin != null && !"".equals(checkin)) {
                    jTextField3.setText(checkin);
                } else {
                    jTextField3.setText(Time());
                }
                jTextField4.setText(checkout);
                jTextField5.setText(total_sum.toString());
            }
        } catch (SQLException ex) {
            Logger.getLogger(Database.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scheme.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables

}
