/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phs.Gui;

import java.io.IOException;
import java.net.BindException;
import java.net.InetAddress;
import java.net.ServerSocket;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import phs.Classes.DBConnector;
import phs.Classes.Database;

/**
 *
 * @author Boznea, Stefan Dimitriu, Alexandru Lazaroiu, Bogdan Nedelea
 */
public class systemgui extends javax.swing.JFrame {

    public static int ok = 0;

    private static final int PORT = 9999;
    private static ServerSocket socket;

   public static void checkIfRunning() {
        try {
            //Bind to localhost adapter with a zero connection queue 
            socket = new ServerSocket(PORT, 0, InetAddress.getByAddress(new byte[]{127, 0, 0, 1}));
        } catch (BindException e) {
            System.err.println("Already running.");
            System.exit(1);
        } catch (IOException e) {
            System.err.println("Unexpected error.");
            System.exit(2);
        }
    }

    public systemgui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        label5 = new java.awt.Label();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 204, 102));
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 204, 102));
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label1.setText("Single Rooms");

        label3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label3.setText("Double Rooms");

        label4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label4.setText("VIP Rooms");

        jButton4.setBackground(new java.awt.Color(0, 204, 102));
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 204, 102));
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        label5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label5.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
        label5.setForeground(new java.awt.Color(51, 102, 255));
        label5.setText("Plaza Hotel");

        jButton6.setBackground(new java.awt.Color(0, 204, 102));
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 204, 102));
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 51, 51));
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 204, 102));
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(0, 204, 102));
        jButton10.setText("10");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(0, 204, 102));
        jButton11.setText("11");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(0, 204, 102));
        jButton12.setText("12");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(0, 204, 102));
        jButton13.setText("13");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(0, 204, 102));
        jButton14.setText("14");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(255, 51, 51));
        jButton15.setText("15");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(0, 204, 102));
        jButton16.setText("16");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(0, 204, 102));
        jButton17.setText("17");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(0, 204, 102));
        jButton18.setText("18");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setBackground(new java.awt.Color(0, 204, 102));
        jButton19.setText("19");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setBackground(new java.awt.Color(0, 204, 102));
        jButton20.setText("20");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setBackground(new java.awt.Color(0, 204, 102));
        jButton21.setText("21");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton22.setBackground(new java.awt.Color(0, 204, 102));
        jButton22.setText("22");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton23.setBackground(new java.awt.Color(0, 204, 102));
        jButton23.setText("23");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton24.setBackground(new java.awt.Color(255, 51, 51));
        jButton24.setText("24");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jButton25.setBackground(new java.awt.Color(0, 204, 102));
        jButton25.setText("25");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jButton26.setBackground(new java.awt.Color(0, 204, 102));
        jButton26.setText("26");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        jButton27.setBackground(new java.awt.Color(255, 51, 51));
        jButton27.setText("27");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jButton28.setBackground(new java.awt.Color(0, 204, 102));
        jButton28.setText("28");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });

        jButton29.setBackground(new java.awt.Color(255, 51, 51));
        jButton29.setText("29");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });

        jButton30.setBackground(new java.awt.Color(0, 204, 102));
        jButton30.setText("30");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });

        jButton31.setBackground(new java.awt.Color(0, 204, 102));
        jButton31.setText("31");
        jButton31.setPreferredSize(new java.awt.Dimension(42, 22));
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });

        jButton32.setBackground(new java.awt.Color(255, 51, 51));
        jButton32.setText("32");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });

        jButton33.setBackground(new java.awt.Color(0, 204, 102));
        jButton33.setText("33");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });

        jButton34.setBackground(new java.awt.Color(0, 204, 102));
        jButton34.setText("34");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });

        jButton35.setBackground(new java.awt.Color(0, 204, 102));
        jButton35.setText("35");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });

        jButton36.setBackground(new java.awt.Color(255, 51, 51));
        jButton36.setText("36");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });

        jButton37.setBackground(new java.awt.Color(0, 204, 102));
        jButton37.setText("37");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });

        jButton38.setBackground(new java.awt.Color(0, 204, 102));
        jButton38.setText("38");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });

        jButton39.setBackground(new java.awt.Color(255, 51, 51));
        jButton39.setText("39");
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });

        jButton40.setBackground(new java.awt.Color(0, 204, 102));
        jButton40.setText("40");
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });

        jButton41.setBackground(new java.awt.Color(255, 255, 0));
        jButton41.setText("41");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });

        jButton42.setBackground(new java.awt.Color(255, 51, 51));
        jButton42.setText("42");
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });

        jButton43.setBackground(new java.awt.Color(255, 255, 0));
        jButton43.setText("43");
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });

        jButton44.setBackground(new java.awt.Color(255, 51, 51));
        jButton44.setText("44");
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });

        jButton45.setBackground(new java.awt.Color(255, 255, 0));
        jButton45.setText("45");
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });

        jButton46.setBackground(new java.awt.Color(255, 255, 0));
        jButton46.setText("46");
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });

        jButton47.setBackground(new java.awt.Color(255, 255, 0));
        jButton47.setText("47");
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });

        jButton48.setBackground(new java.awt.Color(255, 51, 51));
        jButton48.setText("48");
        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton48ActionPerformed(evt);
            }
        });

        jButton49.setBackground(new java.awt.Color(255, 255, 0));
        jButton49.setText("49");
        jButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton49ActionPerformed(evt);
            }
        });

        jButton50.setBackground(new java.awt.Color(255, 255, 0));
        jButton50.setText("50");
        jButton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50ActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton20)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jButton21)
                                    .addComponent(jButton22)
                                    .addComponent(jButton23)
                                    .addComponent(jButton24)
                                    .addComponent(jButton25)
                                    .addComponent(jButton26)
                                    .addComponent(jButton27)
                                    .addComponent(jButton28)
                                    .addComponent(jButton29)
                                    .addComponent(jButton30))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jButton40)
                                    .addComponent(jButton39)
                                    .addComponent(jButton38)
                                    .addComponent(jButton37)
                                    .addComponent(jButton36)
                                    .addComponent(jButton35)
                                    .addComponent(jButton34)
                                    .addComponent(jButton33)
                                    .addComponent(jButton32)
                                    .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jButton50)
                                    .addComponent(jButton49)
                                    .addComponent(jButton48)
                                    .addComponent(jButton47)
                                    .addComponent(jButton46)
                                    .addComponent(jButton45)
                                    .addComponent(jButton44)
                                    .addComponent(jButton43)
                                    .addComponent(jButton42)
                                    .addComponent(jButton41)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)))
                .addContainerGap(246, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton31, jButton32, jButton33, jButton34, jButton35, jButton36, jButton37, jButton38, jButton39, jButton40});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton36)
                                .addGap(7, 7, 7)
                                .addComponent(jButton37)
                                .addGap(7, 7, 7)
                                .addComponent(jButton38)
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton39)
                                    .addComponent(jButton29))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton40)
                                    .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton26)
                                .addGap(7, 7, 7)
                                .addComponent(jButton27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton28))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(jButton16))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(jButton17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton20))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton46)
                        .addGap(7, 7, 7)
                        .addComponent(jButton47)
                        .addGap(7, 7, 7)
                        .addComponent(jButton48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton49)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton50)))
                .addGap(209, 209, 209))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton31, jButton32, jButton33, jButton34, jButton35, jButton36, jButton37, jButton38, jButton39});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ok = 1;

        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ok = 2;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        ok = 15;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        ok = 24;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ok = 3;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ok = 4;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ok = 5;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        ok = 6;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:   
        ok = 7;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:  
        ok = 9;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here: 
        ok = 10;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:        
        ok = 11;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:        
        ok = 12;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:        
        ok = 13;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:        
        ok = 14;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:        
        ok = 16;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:        
        ok = 17;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:        
        ok = 18;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:  
        ok = 19;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        ok = 20;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here: 
        ok = 21;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:   
        ok = 22;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:   
        ok = 23;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here: 
        ok = 25;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:    
        ok = 26;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:   
        ok = 27;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:  
        ok = 28;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:     
        ok = 29;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here: 
        ok = 30;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:  
        ok = 31;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:   
        ok = 32;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        // TODO add your handling code here:    
        ok = 33;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        // TODO add your handling code here:  
        ok = 34;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        // TODO add your handling code here: 
        ok = 35;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        // TODO add your handling code here:        
        ok = 36;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        // TODO add your handling code here:        
        ok = 37;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        // TODO add your handling code here:        
        ok = 38;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        // TODO add your handling code here:        
        ok = 39;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        // TODO add your handling code here:        
        ok = 40;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        // TODO add your handling code here:        
        ok = 41;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        // TODO add your handling code here:        
        ok = 42;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
        // TODO add your handling code here:        
        ok = 43;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton43ActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
        // TODO add your handling code here:        
        ok = 44;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton44ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
        // TODO add your handling code here:
        ok = 45;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
        // TODO add your handling code here: 
        ok = 46;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton46ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
        // TODO add your handling code here:
        ok = 47;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton47ActionPerformed

    private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48ActionPerformed
        // TODO add your handling code here:        
        ok = 48;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton48ActionPerformed

    private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton49ActionPerformed
        // TODO add your handling code here:   
        ok = 49;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton49ActionPerformed

    private void jButton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50ActionPerformed
        // TODO add your handling code here:  
        ok = 50;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton50ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        ok = 8;
        java.awt.EventQueue.invokeLater(() -> {
            new scheme().setVisible(true);
        });
    }//GEN-LAST:event_jButton8ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        checkIfRunning();
        try {
            select();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(systemgui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    public static void update2(int id, String verde) throws SQLException {
        try {//set (subject, priority, status, comment)
            Connection conn = DBConnector.getConnection();
            String query = "UPDATE color SET colour = ? WHERE id = ?";

            System.out.println(query);
            try (PreparedStatement pstmt = conn.prepareStatement(query)) {
                pstmt.setString(1, verde);
                pstmt.setInt(2, id);
                pstmt.executeUpdate();
            }

        } catch (SQLException ex) {
            Logger.getLogger(Database.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static void select() throws ClassNotFoundException {
        try {
            Connection conn = DBConnector.getConnection();
            String sql = "SELECT * FROM color ;";

            System.out.println(sql);
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.executeQuery();

            ResultSet rs = pstmt.getResultSet();
            while (rs.next()) {
                int id = rs.getInt("id");
                String color = rs.getString("colour");
                if (id == 1) {
                    if ("green".equals(color)) {
                        jButton1.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton1.setBackground(new java.awt.Color(255, 0, 0));
                    }
                } else if (id == 2) {
                    if ("green".equals(color)) {
                        jButton2.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton2.setBackground(new java.awt.Color(255, 0, 0));
                    }
                } else if (id == 3) {
                    if ("green".equals(color)) {
                        jButton3.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton3.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 4) {
                    if ("green".equals(color)) {
                        jButton4.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton4.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 5) {
                    if ("green".equals(color)) {
                        jButton5.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton5.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 6) {
                    if ("green".equals(color)) {
                        jButton6.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton6.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 7) {
                    if ("green".equals(color)) {
                        jButton7.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton7.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 8) {
                    if ("green".equals(color)) {
                        jButton8.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton8.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 9) {
                    if ("green".equals(color)) {
                        jButton9.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton9.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 10) {
                    if ("green".equals(color)) {
                        jButton10.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton10.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 11) {
                    if ("green".equals(color)) {
                        jButton11.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton11.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 12) {
                    if ("green".equals(color)) {
                        jButton12.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton12.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 13) {
                    if ("green".equals(color)) {
                        jButton13.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton13.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 14) {
                    if ("green".equals(color)) {
                        jButton14.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton14.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 15) {
                    if ("green".equals(color)) {
                        jButton15.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton15.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 16) {
                    if ("green".equals(color)) {
                        jButton16.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton16.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 17) {
                    if ("green".equals(color)) {
                        jButton17.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton17.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 18) {
                    if ("green".equals(color)) {
                        jButton18.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton18.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 19) {
                    if ("green".equals(color)) {
                        jButton19.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton19.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 20) {
                    if ("green".equals(color)) {
                        jButton20.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton20.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 21) {
                    if ("green".equals(color)) {
                        jButton21.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton21.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 22) {
                    if ("green".equals(color)) {
                        jButton22.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton22.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 23) {
                    if ("green".equals(color)) {
                        jButton23.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton23.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 24) {
                    if ("green".equals(color)) {
                        jButton24.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton24.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 25) {
                    if ("green".equals(color)) {
                        jButton25.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton25.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 26) {
                    if ("green".equals(color)) {
                        jButton26.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton26.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 27) {
                    if ("green".equals(color)) {
                        jButton27.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton27.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 28) {
                    if ("green".equals(color)) {
                        jButton28.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton28.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 29) {
                    if ("green".equals(color)) {
                        jButton29.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton29.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 30) {
                    if ("green".equals(color)) {
                        jButton30.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton30.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 31) {
                    if ("green".equals(color)) {
                        jButton31.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton31.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 32) {
                    if ("green".equals(color)) {
                        jButton32.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton32.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 33) {
                    if ("green".equals(color)) {
                        jButton33.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton33.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 34) {
                    if ("green".equals(color)) {
                        jButton34.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton34.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 35) {
                    if ("green".equals(color)) {
                        jButton35.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton35.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 36) {
                    if ("green".equals(color)) {
                        jButton36.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton36.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 37) {
                    if ("green".equals(color)) {
                        jButton37.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton37.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 38) {
                    if ("green".equals(color)) {
                        jButton38.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton38.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 39) {
                    if ("green".equals(color)) {
                        jButton39.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton39.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 40) {
                    if ("green".equals(color)) {
                        jButton40.setBackground(new java.awt.Color(0, 204, 102));
                    } else if ("red".equals(color)) {
                        jButton40.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 41) {
                    if ("yellow".equals(color)) {
                        jButton41.setBackground(new java.awt.Color(255, 255, 0));
                    } else if ("red".equals(color)) {
                        jButton41.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 42) {
                    if ("yellow".equals(color)) {
                        jButton42.setBackground(new java.awt.Color(255, 255, 0));
                    } else if ("red".equals(color)) {
                        jButton42.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 43) {
                    if ("yellow".equals(color)) {
                        jButton43.setBackground(new java.awt.Color(255, 255, 0));
                    } else if ("red".equals(color)) {
                        jButton43.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 44) {
                    if ("yellow".equals(color)) {
                        jButton44.setBackground(new java.awt.Color(255, 255, 0));
                    } else if ("red".equals(color)) {
                        jButton44.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 45) {
                    if ("yellow".equals(color)) {
                        jButton45.setBackground(new java.awt.Color(255, 255, 0));
                    } else if ("red".equals(color)) {
                        jButton45.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 46) {
                    if ("yellow".equals(color)) {
                        jButton46.setBackground(new java.awt.Color(255, 255, 0));
                    } else if ("red".equals(color)) {
                        jButton46.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 47) {
                    if ("yellow".equals(color)) {
                        jButton47.setBackground(new java.awt.Color(255, 255, 0));
                    } else if ("red".equals(color)) {
                        jButton47.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 48) {
                    if ("yellow".equals(color)) {
                        jButton48.setBackground(new java.awt.Color(255, 255, 0));
                    } else if ("red".equals(color)) {
                        jButton48.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 49) {
                    if ("yellow".equals(color)) {
                        jButton49.setBackground(new java.awt.Color(255, 255, 0));
                    } else if ("red".equals(color)) {
                        jButton49.setBackground(new java.awt.Color(255, 51, 51));
                    }
                } else if (id == 50) {
                    if ("yellow".equals(color)) {
                        jButton50.setBackground(new java.awt.Color(255, 255, 0));
                    } else if ("red".equals(color)) {
                        jButton50.setBackground(new java.awt.Color(255, 51, 51));
                    }
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(Database.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("------------End-----------");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(systemgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new systemgui().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton10;
    public static javax.swing.JButton jButton11;
    public static javax.swing.JButton jButton12;
    public static javax.swing.JButton jButton13;
    public static javax.swing.JButton jButton14;
    public static javax.swing.JButton jButton15;
    public static javax.swing.JButton jButton16;
    public static javax.swing.JButton jButton17;
    public static javax.swing.JButton jButton18;
    public static javax.swing.JButton jButton19;
    public static javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton20;
    public static javax.swing.JButton jButton21;
    public static javax.swing.JButton jButton22;
    public static javax.swing.JButton jButton23;
    public static javax.swing.JButton jButton24;
    public static javax.swing.JButton jButton25;
    public static javax.swing.JButton jButton26;
    public static javax.swing.JButton jButton27;
    public static javax.swing.JButton jButton28;
    public static javax.swing.JButton jButton29;
    public static javax.swing.JButton jButton3;
    public static javax.swing.JButton jButton30;
    public static javax.swing.JButton jButton31;
    public static javax.swing.JButton jButton32;
    public static javax.swing.JButton jButton33;
    public static javax.swing.JButton jButton34;
    public static javax.swing.JButton jButton35;
    public static javax.swing.JButton jButton36;
    public static javax.swing.JButton jButton37;
    public static javax.swing.JButton jButton38;
    public static javax.swing.JButton jButton39;
    public static javax.swing.JButton jButton4;
    public static javax.swing.JButton jButton40;
    public static javax.swing.JButton jButton41;
    public static javax.swing.JButton jButton42;
    public static javax.swing.JButton jButton43;
    public static javax.swing.JButton jButton44;
    public static javax.swing.JButton jButton45;
    public static javax.swing.JButton jButton46;
    public static javax.swing.JButton jButton47;
    public static javax.swing.JButton jButton48;
    public static javax.swing.JButton jButton49;
    public static javax.swing.JButton jButton5;
    public static javax.swing.JButton jButton50;
    public static javax.swing.JButton jButton6;
    public static javax.swing.JButton jButton7;
    public static javax.swing.JButton jButton8;
    public static javax.swing.JButton jButton9;
    private javax.swing.JMenuBar jMenuBar1;
    private java.awt.Label label1;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    // End of variables declaration//GEN-END:variables
}
